package com.amanefer.telegram.util;

import lombok.Getter;

@Getter
public enum UserState {
    PRIMARY,
    CREATE_STOCK,
    SAVE_PRODUCT_INPUT_PRODUCT_TITLE,
    SAVE_PRODUCT,
    MOVE_PRODUCT_INPUT_INVOICE_NUMBER,
    MOVE_PRODUCT_INPUT_STOCK_FROM,
    MOVE_PRODUCT_INPUT_STOCK_TO,
    MOVE_PRODUCT_INPUT_PRODUCT_ARTICLE,
    MOVE_PRODUCT_INPUT_PRODUCT_QUANTITY,
    MOVE_PRODUCT
}
